spring:
  application:
    name: invoice-management

  jpa:
    hibernate:
      ddl-auto: none

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
